# Generated by Django 5.1 on 2024-10-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='joined_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
